In [29]:
from dask.distributed import Client

client = Client(n_workers=4)
client

<Client: 'tcp://127.0.0.1:56793' processes=4 threads=12, memory=7.37 GiB>

2025-10-01 10:32:25,721 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:56814' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {('read-fused-_to_string_dtype-35ee7e5b326e3f456195d94481601f54', 6), ('read-fused-_to_string_dtype-35ee7e5b326e3f456195d94481601f54', 2)} (stimulus_id='handle-worker-cleanup-1759303945.7204585')
2025-10-01 10:32:25,757 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:56815' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {('read-fused-_to_string_dtype-35ee7e5b326e3f456195d94481601f54', 7), ('read-fused-_to_string_dtype-35ee7e5b326e3f456195d94481601f54', 3)} (stimulus_id='handle-worker-cleanup-1759303945.757298')
2025-10-01 10:32:25,761 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:56813' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {('read-fused-_to_string_dtype-35ee7e5b326

In [30]:
import dask.dataframe as dd

ddf = dd.read_csv(
    os.path.join("data", "nycflights", "*.csv"), parse_dates={"Date": [0, 1, 2]}
)
ddf

C:\Users\olenka\AppData\Local\Programs\Python\Python313\Lib\site-packages\dask\dataframe\io\csv.py:594: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  head = reader(BytesIO(b_sample), nrows=sample_rows, **head_kwargs)


Dask DataFrame Structure:
                          Date DayOfWeek  DepTime CRSDepTime  ArrTime CRSArrTime UniqueCarrier FlightNum  TailNum ActualElapsedTime CRSElapsedTime  AirTime ArrDelay DepDelay  Origin    Dest Distance   TaxiIn  TaxiOut Cancelled Diverted
npartitions=10                                                                                                                                                                                                                             
                datetime64[ns]     int64  float64      int64  float64      int64        string     int64  float64           float64          int64  float64  float64  float64  string  string  float64  float64  float64     int64    int64
                           ...       ...      ...        ...      ...        ...           ...       ...      ...               ...            ...      ...      ...      ...     ...     ...      ...      ...      ...       ...      ...
...                        ...       ...      ...        ...      ...        ...           ...       ...      ...               ...            ...      ...      ...      ...     ...     ...      ...      ...      ...       ...      ...
                           ...       ...      ...        ...      ...        ...           ...       ...      ...               ...            ...      ...      ...      ...     ...     ...      ...      ...      ...       ...      ...
                           ...       ...      ...        ...      ...        ...           ...       ...      ...               ...            ...      ...      ...      ...     ...     ...      ...      ...      ...       ...      ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(c4ba1ed))

In [31]:
%run prep.py -d flights

In [32]:
import os
import dask

In [33]:

ddf = dd.read_csv(
    os.path.join("data", "nycflights", "*.csv"),
    parse_dates={"Date": [0, 1, 2]},
    dtype={"TailNum": str, "CRSElapsedTime": float, "Cancelled": bool},
)

C:\Users\olenka\AppData\Local\Programs\Python\Python313\Lib\site-packages\dask\dataframe\io\csv.py:594: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  head = reader(BytesIO(b_sample), nrows=sample_rows, **head_kwargs)


In [35]:
# load and count number of rows
len(ddf)

2611892

In [36]:
ddf.head()

Date  DayOfWeek  DepTime  CRSDepTime  ArrTime  CRSArrTime  \
0 1990-01-01          1   1621.0        1540   1747.0        1701   
1 1990-01-02          2   1547.0        1540   1700.0        1701   
2 1990-01-03          3   1546.0        1540   1710.0        1701   
3 1990-01-04          4   1542.0        1540   1710.0        1701   
4 1990-01-05          5   1549.0        1540   1706.0        1701   

  UniqueCarrier  FlightNum TailNum  ActualElapsedTime  ...  AirTime  ArrDelay  \
0            US         33    <NA>               86.0  ...      NaN      46.0   
1            US         33    <NA>               73.0  ...      NaN      -1.0   
2            US         33    <NA>               84.0  ...      NaN       9.0   
3            US         33    <NA>               88.0  ...      NaN       9.0   
4            US         33    <NA>               77.0  ...      NaN       5.0   

   DepDelay  Origin Dest Distance  TaxiIn  TaxiOut  Cancelled  Diverted  
0      41.0     EWR  PIT    319.0     NaN      NaN      False         0  
1       7.0     EWR  PIT    319.0     NaN      NaN      False         0  
2       6.0     EWR  PIT    319.0     NaN      NaN      False         0  
3       2.0     EWR  PIT    319.0     NaN      NaN      False         0  
4       9.0     EWR  PIT    319.0     NaN      NaN      False         0  

[5 rows x 21 columns]

In [37]:
ddf.tail()

Date  DayOfWeek  DepTime  CRSDepTime  ArrTime  CRSArrTime  \
269176 1999-12-27          1   1645.0        1645   1830.0        1901   
269177 1999-12-28          2   1726.0        1645   1928.0        1901   
269178 1999-12-29          3   1646.0        1645   1846.0        1901   
269179 1999-12-30          4   1651.0        1645   1908.0        1901   
269180 1999-12-31          5   1642.0        1645   1851.0        1901   

       UniqueCarrier  FlightNum TailNum  ActualElapsedTime  ...  AirTime  \
269176            UA       1753  N516UA              225.0  ...    205.0   
269177            UA       1753  N504UA              242.0  ...    214.0   
269178            UA       1753  N592UA              240.0  ...    220.0   
269179            UA       1753  N575UA              257.0  ...    233.0   
269180            UA       1753  N539UA              249.0  ...    232.0   

        ArrDelay  DepDelay  Origin Dest Distance  TaxiIn  TaxiOut  Cancelled  \
269176     -31.0       0.0     LGA  DEN   1619.0     7.0     13.0      False   
269177      27.0      41.0     LGA  DEN   1619.0     5.0     23.0      False   
269178     -15.0       1.0     LGA  DEN   1619.0     5.0     15.0      False   
269179       7.0       6.0     LGA  DEN   1619.0     5.0     19.0      False   
269180     -10.0      -3.0     LGA  DEN   1619.0     6.0     11.0      False   

        Diverted  
269176         0  
269177         0  
269178         0  
269179         0  
269180         0  

[5 rows x 21 columns]

In [38]:
import pandas as pd

files = os.listdir(os.path.join('data', 'nycflights'))

maxes = []

for file in files:
    df = pd.read_csv(os.path.join('data', 'nycflights', file))
    maxes.append(df.DepDelay.max())
    
final_max = max(maxes)

In [39]:
%%time
result = ddf.DepDelay.max()
result.compute()

CPU times: total: 391 ms
Wall time: 1.85 s


np.float64(1435.0)

In [41]:
len(ddf)

2611892

In [43]:
total_non_cancelled = (ddf[ddf["Cancelled"]==0]).shape[0].compute()
print(total_non_cancelled)

2540961


In [ ]:
non

In [44]:
non_canceled = ddf[~ddf.Cancelled]
mean_delay = non_canceled.DepDelay.mean()
std_delay = non_canceled.DepDelay.std()

In [46]:

%%time

mean_delay_res = mean_delay.compute()
std_delay_res = std_delay.compute()

CPU times: total: 1.34 s
Wall time: 4.47 s


In [49]:
%%time

mean_delay_res, std_delay_res = dask.compute(mean_delay, std_delay)

CPU times: total: 672 ms
Wall time: 2.17 s


In [52]:
non_cancelled = ddf[~ddf.Cancelled]
ddf_jfk = non_cancelled[non_cancelled.Origin == "JFK"]

In [53]:
%%time
ddf_jfk.DepDelay.mean().compute()
ddf_jfk.DepDelay.sum().compute()

CPU times: total: 1.55 s
Wall time: 5.19 s


np.float64(4422520.0)

In [54]:
ddf_jfk = ddf_jfk.persist()  # returns back control immediately

In [55]:
%%time
ddf_jfk.DepDelay.mean().compute()
ddf_jfk.DepDelay.std().compute()

CPU times: total: 188 ms
Wall time: 258 ms


np.float64(31.242509798271147)

In [56]:
#| tags: []
help(ddf.map_partitions)

Help on method map_partitions in module dask.dataframe.dask_expr._collection:

map_partitions(
    func,
    *args,
    meta=<no_default>,
    enforce_metadata=True,
    transform_divisions=True,
    clear_divisions=False,
    align_dataframes=False,
    parent_meta=None,
    required_columns=None,
    **kwargs
) method of dask.dataframe.dask_expr._collection.DataFrame instance
    Apply a Python function to each partition

    Parameters
    ----------
    func : function
        Function applied to each partition.
    args, kwargs :
        Arguments and keywords to pass to the function. Arguments and
        keywords may contain ``FrameBase`` or regular python objects.
        DataFrame-like args (both dask and pandas) must have the same
        number of partitions as ``self`` or comprise a single partition.
        Key-word arguments, Single-partition arguments, and general
        python-object arguments will be broadcasted to all partitions.
    enforce_metadata : bool, default 

In [57]:
def my_custom_converter(df, multiplier=1):
    return df * multiplier


meta = pd.Series(name="Distance", dtype="float64")

distance_km = ddf.Distance.map_partitions(
    my_custom_converter, multiplier=0.6, meta=meta
)

In [58]:
client.shutdown()

In [1]:
%run prep.py -d random

- Generating random array data... ** Created random data for array exercise in 75.24s


In [20]:
from dask.distributed import Client

client = Client(n_workers=4)
client

C:\Users\olenka\Desktop\bigdata\.venv\Lib\site-packages\distributed\node.py:187: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 59379 instead
  warnings.warn(


<Client: 'tcp://127.0.0.1:59382' processes=4 threads=12, memory=7.37 GiB>

In [21]:
import numpy as np
import dask.array as da
# NumPy array
a_np = np.ones(10)
a_np

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
a_np_sum = a_np[:5].sum() + a_np[5:].sum()
a_np_suma_da = da.ones(10, chunks=5)


In [23]:
a_da = da.ones(10, chunks=5)
a_da

dask.array<ones_like, shape=(10,), dtype=float64, chunksize=(5,), chunktype=numpy.ndarray>

In [24]:
%%time
xn = np.random.normal(10, 0.1, size=(30_00, 30_00))
yn = xn.mean(axis=0)
yn

CPU times: total: 625 ms
Wall time: 501 ms


array([ 9.9983758 , 10.00184255, 10.00175885, ..., 10.00059162,
        9.99765231,  9.99658552], shape=(3000,))

In [25]:
xd = da.random.normal(10, 0.1, size=(30_00, 30_00), chunks=(300, 300))
xd
xd.nbytes / 1e9  # Gigabytes of the input processed lazily
yd = xd.mean(axis=0)
yd

dask.array<mean_agg-aggregate, shape=(3000,), dtype=float64, chunksize=(300,), chunktype=numpy.ndarray>

In [27]:
%%time
xd = da.random.normal(10, 0.1, size=(30_00, 30_00), chunks=(300, 300))
yd = (xd+xd.T).mean(axis=1)
yd.compute()

CPU times: total: 500 ms
Wall time: 611 ms


array([20.00332166, 19.9991106 , 20.00119249, ..., 20.00115001,
       20.00028194, 19.99967344], shape=(3000,))

In [28]:
darr = da.random.random((1000, 1000, 100))
darr

dask.array<random_sample, shape=(1000, 1000, 100), dtype=float64, chunksize=(409, 409, 100), chunktype=numpy.ndarray>

In [29]:
darr.chunksize

(409, 409, 100)

In [30]:
darr.chunks

((409, 409, 182), (409, 409, 182), (100,))

In [31]:
darr = darr.rechunk({0: -1, 1: 100, 2: "auto"})

darr

darr.chunksize

darr.chunks

((1000,), (100, 100, 100, 100, 100, 100, 100, 100, 100, 100), (100,))

In [32]:
import zarr

a = da.from_zarr("data/random.zarr")

a

dask.array<from-zarr, shape=(200000000,), dtype=float64, chunksize=(6250000,), chunktype=numpy.ndarray>

In [42]:
%%time
a.mean().compute()

CPU times: total: 453 ms
Wall time: 1.23 s


np.float64(0.4999781270014311)

In [43]:
b = da.from_zarr("data/random_sc.zarr")
b

dask.array<from-zarr, shape=(200000000,), dtype=float64, chunksize=(10000,), chunktype=numpy.ndarray>

In [44]:
%%time
b.mean().compute()

CPU times: total: 1min 6s
Wall time: 1min 13s


np.float64(0.5000143488157649)

In [1]:
import xarray as xr

ds = xr.tutorial.open_dataset(
    "air_temperature",
    chunks={  # this tells xarray to open the dataset as a dask array
        "lat": 25,
        "lon": 25,
        "time": -1,
    },
)
ds

ds.air

ds.air.chunks

mean = ds.air.mean("time")  # no activity on dashboard
mean  # contains a dask array

# we will see dashboard activity
mean.load()

<xarray.DataArray 'air' (lat: 25, lon: 53)> Size: 11kB
array([[260.37644178, 260.18305137, 259.88662671, ..., 250.81590068,
        251.93811644, 253.43804795],
       [262.73439384, 262.79397603, 262.74933904, ..., 249.75590411,
        251.58575685, 254.35926027],
       [264.7687637 , 264.32730822, 264.06169521, ..., 250.60789041,
        253.58351027, 257.71559932],
       ...,
       [297.64986301, 296.95333219, 296.62931507, ..., 296.81092466,
        296.28796233, 295.81645548],
       [298.12920205, 297.93700685, 297.47039384, ..., 296.85954795,
        296.7770274 , 296.44383562],
       [298.36615068, 298.38573973, 298.11414384, ..., 297.33820548,
        297.28144521, 297.30510274]], shape=(25, 53))
Coordinates:
  * lat      (lat) float32 100B 75.0 72.5 70.0 67.5 65.0 ... 22.5 20.0 17.5 15.0
  * lon      (lon) float32 212B 200.0 202.5 205.0 207.5 ... 325.0 327.5 330.0

In [2]:
dair = ds.air

dair2 = dair.groupby("time.month").mean("time")
dair_new = dair - dair2
dair_new

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53, month: 12)> Size: 371MB
dask.array<sub, shape=(2920, 25, 53, 12), dtype=float64, chunksize=(2920, 25, 25, 1), chunktype=numpy.ndarray>
Coordinates:
  * lat      (lat) float32 100B 75.0 72.5 70.0 67.5 65.0 ... 22.5 20.0 17.5 15.0
  * lon      (lon) float32 212B 200.0 202.5 205.0 207.5 ... 325.0 327.5 330.0
  * time     (time) datetime64[ns] 23kB 2013-01-01 ... 2014-12-31T18:00:00
  * month    (month) int64 96B 1 2 3 4 5 6 7 8 9 10 11 12

In [3]:
# things happen in the dashboard
dair_new.load()

<xarray.DataArray 'air' (time: 2920, lat: 25, lon: 53, month: 12)> Size: 371MB
array([[[[-5.14975806e+00, -5.47709821e+00, -9.83161290e+00, ...,
          -2.06137097e+01, -1.25446667e+01, -6.77088710e+00],
         [-3.88592742e+00, -3.90562500e+00, -8.17975806e+00, ...,
          -1.87126210e+01, -1.11448750e+01, -5.52096774e+00],
         [-2.71495968e+00, -2.44830357e+00, -6.68943548e+00, ...,
          -1.70037097e+01, -9.99704167e+00, -4.41282258e+00],
         ...,
         [-1.02609677e+01, -9.05825893e+00, -9.39375000e+00, ...,
          -1.53932661e+01, -1.01605833e+01, -6.97169355e+00],
         [-8.58774194e+00, -7.50187500e+00, -7.61467742e+00, ...,
          -1.35697581e+01, -8.43441667e+00, -5.52358871e+00],
         [-7.04653226e+00, -5.84366071e+00, -5.70947581e+00, ...,
          -1.18160887e+01, -6.54195833e+00, -4.02806452e+00]],

        [[-5.05750000e+00, -3.99995536e+00, -9.17193548e+00, ...,
          -2.52225000e+01, -1.53297500e+01, -5.93338710e+00],
         [-4.40729839e+00, -3.25986607e+00, -8.36620968e+00, ...,
          -2.44295565e+01, -1.41292083e+01, -5.66028226e+00],
         [-4.01028226e+00, -2.77741071e+00, -7.87350806e+00, ...,
          -2.40149194e+01, -1.34914583e+01, -5.78564516e+00],
...
          -3.56907258e+00, -2.47420833e+00, -1.16564516e+00],
         [ 6.08588710e-01,  1.47191964e+00,  1.11951613e+00, ...,
          -3.59879032e+00, -2.50400000e+00, -1.15669355e+00],
         [ 6.59838710e-01,  1.48723214e+00,  1.03766129e+00, ...,
          -3.84629032e+00, -2.71833333e+00, -1.33141129e+00]],

        [[ 5.35524194e-01,  4.00892857e-01,  3.08104839e-01, ...,
          -1.68060484e+00, -1.12145833e+00, -1.90927419e-01],
         [ 8.51572581e-01,  8.73303571e-01,  6.26653226e-01, ...,
          -1.33471774e+00, -7.66625000e-01,  1.03225806e-01],
         [ 1.04084677e+00,  1.23178571e+00,  8.63104839e-01, ...,
          -1.06616935e+00, -5.31083333e-01,  3.14475806e-01],
         ...,
         [ 4.71854839e-01,  1.32928571e+00,  1.15487903e+00, ...,
          -3.23411290e+00, -2.23962500e+00, -1.11032258e+00],
         [ 4.14193548e-01,  1.23397321e+00,  1.07866935e+00, ...,
          -3.47326613e+00, -2.56187500e+00, -1.37540323e+00],
         [ 5.32258065e-02,  8.10000000e-01,  6.73266129e-01, ...,
          -4.07241935e+00, -3.12895833e+00, -1.84770161e+00]]]],
      shape=(2920, 25, 53, 12))
Coordinates:
  * lat      (lat) float32 100B 75.0 72.5 70.0 67.5 65.0 ... 22.5 20.0 17.5 15.0
  * lon      (lon) float32 212B 200.0 202.5 205.0 207.5 ... 325.0 327.5 330.0
  * time     (time) datetime64[ns] 23kB 2013-01-01 ... 2014-12-31T18:00:00
  * month    (month) int64 96B 1 2 3 4 5 6 7 8 9 10 11 12

In [4]:
client.shutdown()

NameError: name 'client' is not defined